- name: google
  userType: org
  file: google.md
- name: apple
  userType: org
  file: apple.md
- name: alibaba
  userType: org
  file: alibaba.md
- name: facebook
  userType: org
  file: facebook.md
- name: pingcap
  userType: org
  file: pingcap.md
- name: sony
  userType: org
  file: sony.md
- name: apache
  userType: org
  file: apache.md
- name: openai
  userType: org
  file: openai.md
- name: tensorflow
  userType: org
  file: tensorflow.md
- name: bytedance
  userType: org
  file: bytedance.md
- name: elastic
  userType: org
  file: elastic.md
- name: tencent
  userType: org
  file: tencent.md
- name: netflix
  userType: org
  file: netflix.md
- name: deepmind
  userType: org
  file: deepmind.md
- name: google-research
  userType: org
  file: google-research.md
- name: openjdk
  userType: org
  file: openjdk.md
- name: oracle
  userType: org
  file: oracle.md
- name: microsoft
  userType: org
  file: microsoft.md
- name: github
  userType: org
  file: github.md
- name: mozilla
  userType: org
  file: mozilla.md
- name: eclipse
  userType: org
  file: eclipse.md
- name: cloudfoundry
  userType: org
  file: cloudfoundry.md
- name: openstack
  userType: org
  file: openstack.md
- name: opencollective
  userType: org
  file: opencollective.md
