- name: google
  userType: org
  file: google.md
- name: apple
  userType: org
  file: apple.md
- name: alibaba
  userType: org
  file: alibaba.md
- name: facebook
  userType: org
  file: facebook.md
- name: pingcap
  userType: org
  file: pingcap.md
- name: sony
  userType: org
  file: sony.md
- name: apache
  userType: org
  file: apache.md
- name: openai
  userType: org
  file: openai.md
- name: tensorflow
  userType: org
  file: tensorflow.md
- name: bytedance
  userType: org
  file: bytedance.md
- name: elastic
  userType: org
  file: elastic.md
- name: tencent
  userType: org
  file: tencent.md
- name: netflix
  userType: org
  file: netflix.md
- name: deepmind
  userType: org
  file: deepmind.md
- name: google-research
  userType: org
  file: google-research.md
- name: openjdk
  userType: org
  file: openjdk.md
- name: oracle
  userType: org
  file: oracle.md
- name: microsoft
  userType: org
  file: microsoft.md
- name: github
  userType: org
  file: github.md
- name: mozilla
  userType: org
  file: mozilla.md
- name: eclipse
  userType: org
  file: eclipse.md
- name: cloudfoundry
  userType: org
  file: cloudfoundry.md
- name: openstack
  userType: org
  file: openstack.md
- name: opencollective
  userType: org
  file: opencollective.md
- name: twitter-archive
  userType: org
  file: twitter-archive.md
- name: twitter
  userType: org
  file: twitter.md
- name: cloudflare
  userType: org
  file: cloudflare.md
- name: golang
  userType: org
  file: golang.md
- name: rust-lang
  userType: org
  file: rust-lang.md
- name: intel
  userType: org
  file: intel.md
- name: ARM-software
  userType: org
  file: ARM-software.md
- name: riscv
  userType: org
  file: riscv.md
- name: microsoftgraph
  userType: org
  file: microsoftgraph.md
- name: tuna
  userType: org
  file: tuna.md
- name: ustclug
  userType: org
  file: ustclug.md
- name: NVIDIA
  userType: org
  file: NVIDIA.md
- name: efforg
  userType: org
  file: efforg.md
- name: facebookresearch
  userType: org
  file: facebookresearch.md
- name: wikimedia
  userType: org
  file: wikimedia.md
- name: awslabs
  userType: org
  file: awslabs.md
- name: w3c
  userType: org
  file: w3c.md
- name: spring-projects
  userType: org
  file: spring-projects.md
- name: uber
  userType: org
  file: uber.md
- name: apachecn
  userType: org
  file: apachecn.md
- name: opengenus
  userType: org
  file: opengenus.md
- name: baidu 
  userType: org
  file: baidu.md
- name: WICG
  userType: WICG
  file: WICG.md
- name: JetBrains
  userType: org
  file: JetBrains.md
- name: hashicorp
  userType: org
  file: hashicorp.md
- name: Azure
  userType: org
  file: Azure.md
- name: mdn
  userType: org
  file: mdn.md

