- name: google
  userType: org
  file: google.md
- name: apple
  userType: org
  file: apple.md
- name: alibaba
  userType: org
  file: alibaba.md
- name: facebook
  userType: org
  file: facebook.md
- name: pingcap
  userType: org
  file: pingcap.md
- name: sony
  userType: org
  file: sony.md
- name: apache
  userType: org
  file: apache.md
- name: openai
  userType: org
  file: openai.md
- name: apple
  userType: org
  file: apple.md
- name: tensorflow
  userType: org
  file: tensorflow.md
- name: bytedance
  userType: org
  file: bytedance.md
- name: elastic
  userType: org
  file: elastic.md
