- name: riscv
  userType: org
  file: riscv.md
- name: sony
  userType: org
  file: sony.md
- name: tuna
  userType: org
  file: tuna.md
- name: twitter-archive
  userType: org
  file: twitter-archive.md
- name: opengenus
  userType: org
  file: opengenus.md
- name: efforg
  userType: org
  file: efforg.md
- name: twitter
  userType: org
  file: twitter.md
- name: facebook
  userType: org
  file: facebook.md
- name: pingcap
  userType: org
  file: pingcap.md
- name: openai
  userType: org
  file: openai.md
- name: uber
  userType: org
  file: uber.md
- name: rust-lang
  userType: org
  file: rust-lang.md
- name: google-research
  userType: org
  file: google-research.md
- name: NVIDIA
  userType: org
  file: NVIDIA.md
- name: microsoftgraph
  userType: org
  file: microsoftgraph.md
- name: github
  userType: org
  file: github.md
- name: cloudfoundry
  userType: org
  file: cloudfoundry.md
- name: nasa
  userType: org
  file: nasa.md
- name: facebookresearch
  userType: org
  file: facebookresearch.md
- name: JetBrains
  userType: org
  file: JetBrains.md
- name: openstack
  userType: org
  file: openstack.md
- name: intel
  userType: org
  file: intel.md
- name: opencollective
  userType: org
  file: opencollective.md
- name: google
  userType: org
  file: google.md
- name: mozilla
  userType: org
  file: mozilla.md
- name: microsoft
  userType: org
  file: microsoft.md
