- name: golang
  userType: org
  file: golang.md
- name: ustclug
  userType: org
  file: ustclug.md
- name: openjdk
  userType: org
  file: openjdk.md
- name: baidu 
  userType: org
  file: baidu.md
- name: mdn
  userType: org
  file: mdn.md
- name: tensorflow
  userType: org
  file: tensorflow.md
- name: deepmind
  userType: org
  file: deepmind.md
- name: ARM-software
  userType: org
  file: ARM-software.md
- name: apple
  userType: org
  file: apple.md
- name: spring-projects
  userType: org
  file: spring-projects.md
- name: bytedance
  userType: org
  file: bytedance.md
- name: tencent
  userType: org
  file: tencent.md
- name: netflix
  userType: org
  file: netflix.md
- name: oracle
  userType: org
  file: oracle.md
- name: cloudflare
  userType: org
  file: cloudflare.md
- name: alibaba
  userType: org
  file: alibaba.md
- name: apachecn
  userType: org
  file: apachecn.md
- name: eclipse
  userType: org
  file: eclipse.md
- name: elastic
  userType: org
  file: elastic.md
- name: awslabs
  userType: org
  file: awslabs.md
- name: hashicorp
  userType: org
  file: hashicorp.md
- name: w3c
  userType: org
  file: w3c.md
- name: Azure
  userType: org
  file: Azure.md
- name: apache
  userType: org
  file: apache.md
- name: wikimedia
  userType: org
  file: wikimedia.md
